# This file was generated by GoReleaser. DO NOT EDIT.
class Cldnt < Formula
  desc "Software for getting the closest airports."
  homepage "https://github.com/oleewere"
  version "0.2.0"

  if OS.mac?
    url "https://github.com/oleewere/cldnt/releases/download/v0.2.0/cldnt_0.2.0_macOS_64-bit.tar.gz"
    sha256 "a9d600c180444c4ecaaf9629ff7d5a990762f8953de296b48b46598c2122351e"
  elsif OS.linux?
    url "https://github.com/oleewere/cldnt/releases/download/v0.2.0/cldnt_0.2.0_linux_64-bit.tar.gz"
    sha256 "cf6e68356de5df8fe9a22e4f767a1e2e02738026b59d8a45e06130060796bcf1"
  end

  def install
    bin.install "cldnt"
  end

  test do
    system "#{bin}/cldnt --version"
  end
end
