# This file was generated by GoReleaser. DO NOT EDIT.
class Meteringp < Formula
  desc "Software for generating metering events."
  homepage "https://github.com/oleewere"
  version "0.1.0"

  if OS.mac?
    url "https://github.com/oleewere/meteringp/releases/download/v0.1.0/meteringp_0.1.0_macOS_64-bit.tar.gz"
    sha256 "b1fedc22b389271a810d41cf02b406ef8f887da446b801a457858f6fbf3387da"
  elsif OS.linux?
    url "https://github.com/oleewere/meteringp/releases/download/v0.1.0/meteringp_0.1.0_linux_64-bit.tar.gz"
    sha256 "605ad5b9386def0f8fbad4f7c45068d4efda8e93118ac04fe08defdc7cd436c9"
  end

  def install
    bin.install "meretingp"
  end

  test do
    system "#{bin}/meteringp --version"
  end
end
