# This file was generated by GoReleaser. DO NOT EDIT.
class Meteringp < Formula
  desc "Software for generating metering events."
  homepage "https://github.com/oleewere"
  version "0.2.0"

  if OS.mac?
    url "https://github.com/oleewere/meteringp/releases/download/v0.2.0/meteringp_0.2.0_macOS_64-bit.tar.gz"
    sha256 "f9bc053594b8800134d63c72f5ec43b38487eb06cb111d1eb85c0908dd05b2ac"
  elsif OS.linux?
    url "https://github.com/oleewere/meteringp/releases/download/v0.2.0/meteringp_0.2.0_linux_64-bit.tar.gz"
    sha256 "36faa9ade1ff44c0be4349e605dfad4ede8a4d60c29618839622b2b300d64e16"
  end

  def install
    bin.install "meteringp"
  end

  test do
    system "#{bin}/meteringp --version"
  end
end
