# This file was generated by GoReleaser. DO NOT EDIT.
class Meteringp < Formula
  desc "Software for generating metering events."
  homepage "https://github.com/oleewere"
  version "0.1.0"

  if OS.mac?
    url "https://github.com/oleewere/meteringp/releases/download/v0.1.0/meteringp_0.1.0_macOS_64-bit.tar.gz"
    sha256 "bb3375adb7c4e58a8da3c5b7b918dce3f7ebb4d586a03a42d902b22f6962b0e5"
  elsif OS.linux?
    url "https://github.com/oleewere/meteringp/releases/download/v0.1.0/meteringp_0.1.0_linux_64-bit.tar.gz"
    sha256 "808c92c46cea1921090d545676ed7218dc2ff6e1d7e4756bbf0990329f42ce75"
  end

  def install
    bin.install "meteringp"
  end

  test do
    system "#{bin}/meteringp --version"
  end
end
